//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class IzdanjaKnjiga
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IzdanjaKnjiga()
        {
            this.PrimjerciKnjiga = new HashSet<PrimjerciKnjiga>();
        }
    
        public int Id { get; set; }



        [Required(ErrorMessage = "Obavezno je izabrati knjigu")]
        public int KnjigeId { get; set; }
        
        
        
        
        [Required(ErrorMessage = "Obavezno je izabrati izdavacku kucu")]
        public int IzdavackaKucaId { get; set; }
        
        
        
        //[Required(ErrorMessage = "Obavezno je izabrati sliku korica")]
        public string SlikaKorica { get; set; }
        
        
        
        [Required(ErrorMessage = "Obavezno je izabrati godinu")]
        public int Godina { get; set; }
        
        
        
        [Required(ErrorMessage = "Obavezno je unijeti broj na stanju")]
        public int BrojNaStanju { get; set; }


        [Required(ErrorMessage = "Obavezno je unijeti broj izdatih")]
        public int BrojIzdatih { get; set; }
    
        public virtual IzdavackeKuce IzdavackeKuce { get; set; }
        public virtual Knjige Knjige { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrimjerciKnjiga> PrimjerciKnjiga { get; set; }
    }
}
