//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Knjige
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Knjige()
        {
            this.IzdanjaKnjiga = new HashSet<IzdanjaKnjiga>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "Naslov knjige je obavezno polje")]
        public string Naslov { get; set; }

        
        [Required(ErrorMessage = "Ime autora je obavezno")]
        public int AutorId { get; set; }
        [Required(ErrorMessage = "Godina originala je obavezno polje")]
        public int GodinaOriginala { get; set; }
        [Required(ErrorMessage = "Kategorija je obavezno polje")]
        public int KategorijaId { get; set; }
        [Required(ErrorMessage = "Broj na stanju je obavezno polje")]
        public int BrojNaStanju { get; set; }
        [Required(ErrorMessage = "Broj izdatih je obavezno polje")]
        public int BrojIzdatih { get; set; }
    
        public virtual Autori Autori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzdanjaKnjiga> IzdanjaKnjiga { get; set; }
        public virtual Kategorije Kategorije { get; set; }
    }
}
